[project]
name = "StreetSmart_API"
version = "0.1.0"
description = "backend for the flutter app"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
    "django-ninja>=1.4.5",
    "opening-hours-py>=1.1.3",
    "psycopg2-binary>=2.9.9",
]
