# Generated by Django 5.2.7 on 2025-10-26 21:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', 'enable_gis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedestrianWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_id', models.BigIntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('highway', models.TextField(blank=True, null=True)),
                ('lit', models.TextField(blank=True, null=True)),
                ('sidewalk', models.TextField(blank=True, null=True)),
                ('surface', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=3857)),
            ],
            options={
                'db_table': 'safety_osm_lines',
            },
        ),
        migrations.CreateModel(
            name='SafetyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way_id', models.BigIntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('amenity', models.TextField(blank=True, null=True)),
                ('shop', models.TextField(blank=True, null=True)),
                ('landuse', models.TextField(blank=True, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=3857)),
            ],
            options={
                'db_table': 'safety_osm_polygons',
            },
        ),
        migrations.CreateModel(
            name='SafetyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.BigIntegerField()),
                ('name', models.TextField(blank=True, null=True)),
                ('amenity', models.TextField(blank=True, null=True)),
                ('shop', models.TextField(blank=True, null=True)),
                ('highway', models.TextField(blank=True, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=3857)),
            ],
            options={
                'db_table': 'safety_osm_points',
            },
        ),
    ]
