# Generated by Django 5.2.7 on 2025-10-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedestrianway',
            name='id',
        ),
        migrations.RemoveField(
            model_name='safetyarea',
            name='id',
        ),
        migrations.RemoveField(
            model_name='safetypoint',
            name='id',
        ),
        migrations.AddField(
            model_name='pedestrianway',
            name='safety_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedestrianway',
            name='way_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='safetyarea',
            name='way_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='safetypoint',
            name='node_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
