# Generated by Django 5.2.7 on 2025-10-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pedestrianway_id_remove_safetyarea_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedestrianway',
            old_name='safety_score',
            new_name='daytime_safety_score',
        ),
        migrations.AddField(
            model_name='pedestrianway',
            name='nighttime_safety_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
