# Generated by Django 5.2.7 on 2025-10-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_safety_score_pedestrianway_daytime_safety_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedestrianway',
            name='source',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedestrianway',
            name='target',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
