# Generated by Django 5.2.7 on 2025-10-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedestrianway_source_pedestrianway_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedestrianway',
            name='reasons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
